logging:
  level:
    root: error

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: "jdbc:mysql://mysql-db:3306/ranking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true"
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  host: "redis-db"
  port: "6379"