logging:
  level:
    root: info

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: "jdbc:mysql://order-db:3306/order-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true"
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    stream:
      bindings:
        order-create: # bindingName
          destination: order-create # 토픽 이름
          content-type: application/json
      kafka:
        binder:
          brokers: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
        bindings:
          order-create:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer