logging:
  level:
    root: info

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: "jdbc:mysql://item-db:3306/item-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true"
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    stream:
      function:
        definition: minusQuantity;
      bindings:
        minusQuantity-in-0:
          destination: order-create
      kafka:
        binder:
          brokers: "kafka-1:9092,kafka-2:9092,kafka-3:9092"