version: "3"

services:
  db-mysql-cqrs:
    image: mysql
    container_name: db-mysql-cqrs
    environment:
      MYSQL_DATABASE: cqrs
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # volumes:
    # - file path
    networks:
      - cqrs-network

  db-redis-cqrs:
    image: redis
    container_name: db-redis-cqrs
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cqrs-network

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'
    networks:
      - cqrs-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - cqrs-network

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.3.0
    ports:
      - '8083:8083'
    volumes:
      - ./connectors:/etc/kafka-connect/jars/
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: connect-group
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-statuses
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
    depends_on:
      - kafka
      - schema-registry
      - db-mysql-cqrs
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt debezium/debezium-connector-mysql:latest
        /etc/confluent/docker/run
    networks:
      - cqrs-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    ports:
      - '8081:8081'
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    networks:
      - cqrs-network

  debezium-ui:
    image: debezium/debezium-ui
    container_name: debezium-ui
    hostname: debezium-ui
    depends_on:
      - kafka-connect
    ports:
      - '8090:8080'
    environment:
      KAFKA_CONNECT_URIS: http://kafka-connect:8083
    networks:
      - cqrs-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: cqrs-kafka-ui
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - kafka-connect
      - schema-registry
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=kafka-connect
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://kafka-connect:8083
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081
    networks:
      - cqrs-network

  cqrs-app:
    container_name: cqrs-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9090:9090'
    depends_on:
      - db-mysql-cqrs
      - db-redis-cqrs
      - kafka
    environment:
      spring.datasource.url: "jdbc:mysql://db-mysql-cqrs:3306/cqrs?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    networks:
      - cqrs-network

networks:
  cqrs-network:
    driver: bridge