version: "3"

services:
  db-mysql-cqrs:
    image: mysql
    container_name: db-mysql-cqrs
    environment:
      MYSQL_DATABASE: cqrs
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # volumes:
    # - file path
    networks:
      - cqrs-network
  cqrs-app:
    container_name: cqrs-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db-mysql-cqrs
    environment:
      spring.datasource.url: "jdbc:mysql://db-mysql-cqrs:3306/cqrs?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    networks:
      - cqrs-network

networks:
  cqrs-network:
    driver: bridge