version: "3"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ranking
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    networks:
      - ranking-network

  redis-db:
    image: redis
    container_name: redis-db
    ports:
      - '6379:6379'
    networks:
      - ranking-network

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql-db
      - redis-db
    networks:
      - ranking-network

networks:
  ranking-network:
    driver: bridge
