logging:
  level:
    root: info

spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: "jdbc:mysql://localhost:3306/concurrency?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true"
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  host: "localhost"
  port: "6379"